extra-include-dirs:
- /usr/local/opt/ncurses/include
extra-lib-dirs:
- /usr/local/opt/ncurses/lib
flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- brick-0.26
- word-wrap-0.4.1
resolver: lts-9.13
